### ISSUE TITLE
[BUG] Crashing upon opening world.

### ISSUE THREAD

**Issue by Mysteriaa** [DaFuqs/StarrySky#17] opened 2021-02-24 00:31 UTC
**Describe the bug**
Opening a world with this mod installed causes the game to disconnect you from your own Singleplayer world with "server closed", or crashes the game outright. NotEnoughCrashes blames this mod and some kind of Fabric lifecycle thing.

**To Reproduce**
Open world with SS installed

**Expected behavior**
I mean... I was expecting the game to not crash?

**Screenshots**
Crash log: 
[crash-2021-02-23_19.03.54-server.txt](https://github.com/DaFuqs/StarrySky/files/6032531/crash-2021-02-23_19.03.54-server.txt)

**Comment by DaFuqs** [comment] 2021-02-24 07:53
I encountered that one yesterday!
When adding the mod the Starry Sky dimensions are not loaded at all. That results in a crash when checking if a player is in one of the Starry dimensions.
 
SS seems to use a custom way to inject it's world into the game. Since starry dimension loading uses the vanilla experimental world format I wonder what the actual source of the problem is.

Can you test an instance without Starry (so no crash) and check if the Bumblezone dimension can be loaded? That one uses the experimental vanilla dimension type, too.

**Comment by Mysteriaa** [comment] 2021-02-24 14:12
> Can you test an instance without Starry (so no crash) and check if the Bumblezone dimension can be loaded? That one uses the experimental vanilla dimension type, too.

Just tried this out with only Bumblezone installed and booted up a Creative world. No crash occurs.

I installed Starry Skies as well and no crash occurred in that same world, curiously enough. Started another new world in survival and still no crash. Odd.

**Comment by DaFuqs** [comment] 2021-02-25 18:16
I think I know where the issue lies then! The astromine team once had the same problem. It's because of vanillas custom world json api (that bumblezone, starry and astromine use) is still very WIP and under some circumstances (that are unknown to me; maybe other mods adding dimensions without using json?) don't load json dimensions correctly. I think I once saw an entry on the vanilla bug tracker, but can't find it atm. Maybe it has since been closed in the recent snapshots.

Anyway: At least I could add a check if the Starry Dims were not loaded, logging an error instead of outright crashing.

**Closed by DaFuqs** 2021-02-25 18:16 UTC
Labels: bug
